name: conFusion
on:
  push:
    branches:
      - codeDeploy
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "wagheakshu@gmail.com"
        git config --global user.name "akshataw"
        git remote set-url origin https://41fc30d07ec44417e1a034ca9296af5a3fd0f89b@github.com/akshataw/confusionReact.git
        npm run deploy